In [1]:
import numpy as np
windows = np.load("../data/windows.npy")
print(windows.shape)

(900, 23, 1024)


In [2]:
labels = np.zeros(len(windows), dtype=int)
print(labels.shape)

(900,)


In [3]:
# labels[749:760] = 1

In [4]:
labels = np.zeros(len(windows), dtype=int)
print(labels.shape)

(900,)


In [5]:
labels[749:760]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
print("Total Windows :", len(labels))
print("Seizure Windows :", np.sum(labels))
print("Normal Windows :", len(labels) - np.sum(labels))

Total Windows : 900
Seizure Windows : 0
Normal Windows : 900


In [7]:
print(labels[745:765])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [8]:
np.save("../data/labels.npy", labels)
print("Labels Saved Successfully")

Labels Saved Successfully


In [9]:
import os 
data_folder = "../data/chb01"

edf_files = sorted([
    file for file in os.listdir(data_folder)
    if file.endswith(".edf")
])
print("Number of EDF files:", len(edf_files))

Number of EDF files: 15


In [10]:
for file in edf_files:
    print(file)

chb01_01.edf
chb01_03.edf
chb01_04.edf
chb01_09.edf
chb01_15.edf
chb01_18.edf
chb01_21.edf
chb01_26.edf
chb01_30.edf
chb01_38.edf
chb01_39.edf
chb01_40.edf
chb01_41.edf
chb01_42.edf
chb01_46.edf


In [11]:
import mne 
import os
for file in edf_files:
    file_path = os.path.join(data_folder, file)
    raw = mne.io.read_raw_edf(file_path, preload=False, verbose=False)
    print(file, "->", raw.info["sfreq"], "Hz")

chb01_01.edf -> 256.0 Hz
chb01_03.edf -> 256.0 Hz
chb01_04.edf -> 256.0 Hz
chb01_09.edf -> 256.0 Hz
chb01_15.edf -> 256.0 Hz
chb01_18.edf -> 256.0 Hz
chb01_21.edf -> 256.0 Hz
chb01_26.edf -> 256.0 Hz
chb01_30.edf -> 256.0 Hz
chb01_38.edf -> 256.0 Hz
chb01_39.edf -> 256.0 Hz
chb01_40.edf -> 256.0 Hz
chb01_41.edf -> 256.0 Hz
chb01_42.edf -> 256.0 Hz
chb01_46.edf -> 256.0 Hz


C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3822119585.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=False, verbose=False)
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3822119585.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=False, verbose=False)
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3822119585.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(file_path, preload=False, verbose=False)
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3822119585.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
 

In [12]:
import mne 
import os
for file in edf_files:
    file_path = os.path.join(data_folder, file)
    raw = mne.io.read_raw_edf(
        file_path,
        preload=False,
        verbose=False
    )
    duration = raw.n_times / raw.info["sfreq"]
    print(file, "->", duration, "seconds")
    

C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3564530741.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3564530741.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(


chb01_01.edf -> 3600.0 seconds
chb01_03.edf -> 3600.0 seconds
chb01_04.edf -> 3600.0 seconds
chb01_09.edf -> 3600.0 seconds
chb01_15.edf -> 3600.0 seconds
chb01_18.edf -> 3600.0 seconds
chb01_21.edf -> 3600.0 seconds
chb01_26.edf -> 2325.0 seconds
chb01_30.edf -> 3600.0 seconds
chb01_38.edf -> 3600.0 seconds
chb01_39.edf -> 3600.0 seconds
chb01_40.edf -> 3600.0 seconds
chb01_41.edf -> 3600.0 seconds
chb01_42.edf -> 3600.0 seconds
chb01_46.edf -> 3600.0 seconds


C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3564530741.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3564530741.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3564530741.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3564530741.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\3564530741.py:5: RuntimeWarning

In [13]:
import mne
import os
for file in edf_files:
    file_path = os.path.join(data_folder, file)
    raw = mne.io.read_raw_edf(
    file_path,
    preload=False,
    verbose=False
    )
    print(file, "->", len(raw.ch_names),"channels")

C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\2618079871.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(


chb01_01.edf -> 23 channels


C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\2618079871.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\2618079871.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(


chb01_03.edf -> 23 channels
chb01_04.edf -> 23 channels
chb01_09.edf -> 23 channels
chb01_15.edf -> 23 channels
chb01_18.edf -> 23 channels
chb01_21.edf -> 23 channels
chb01_26.edf -> 23 channels
chb01_30.edf -> 23 channels
chb01_38.edf -> 23 channels
chb01_39.edf -> 23 channels
chb01_40.edf -> 23 channels
chb01_41.edf -> 23 channels
chb01_42.edf -> 23 channels
chb01_46.edf -> 23 channels


C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\2618079871.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\2618079871.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\2618079871.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\2618079871.py:5: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf(
C:\Users\Prajapati_Shivam\AppData\Local\Temp\ipykernel_16704\2618079871.py:5: RuntimeWarning

In [14]:
seizure_start = 2996
seizure_end = 3036

print("Seizure Start:", seizure_start, "seconds")
print("Seizure End:", seizure_end, "seconds")

Seizure Start: 2996 seconds
Seizure End: 3036 seconds


In [15]:
labels = np.zeros(len(windows), dtype=int)
print("Total Windows:", len(labels))

Total Windows: 900


In [16]:
window_duration = 4
for i in range(len(windows)):
    window_start = i*window_duration
    window_end = window_start + window_duration

    if window_start < seizure_end and window_end > seizure_start:
        labels[i] = 1

In [17]:
print("Total Windows :", len(labels))
print("Seizure Windows :", np.sum(labels))
print("Normal Windows :", len(labels) - np.sum(labels))

Total Windows : 900
Seizure Windows : 10
Normal Windows : 890


In [18]:
seizure_indices = np.where(labels == 1)[0]
print("Seizure Windows Indices:")
print(seizure_indices)

Seizure Windows Indices:
[749 750 751 752 753 754 755 756 757 758]


In [19]:
for i in seizure_indices:
    start = i*window_duration
    end = start + window_duration

    print(
    f"Window {i}:"
    f"{start}-{end} seconds"
    )

Window 749:2996-3000 seconds
Window 750:3000-3004 seconds
Window 751:3004-3008 seconds
Window 752:3008-3012 seconds
Window 753:3012-3016 seconds
Window 754:3016-3020 seconds
Window 755:3020-3024 seconds
Window 756:3024-3028 seconds
Window 757:3028-3032 seconds
Window 758:3032-3036 seconds


In [20]:
print("Last seizure window:")
i = seizure_indices[-1]
start = i*window_duration
end = start + window_duration
print(F"Window {i}: {start}-{end} seconds")


Last seizure window:
Window 758: 3032-3036 seconds


In [21]:
np.save("../data/labels.npy", labels)
print("Labels saved successfully!")

Labels saved successfully!


In [22]:
loaded_labels = np.load("../data/labels.npy")

print("Loaded labels shape:", loaded_labels.shape)
print("Total windows:", len(loaded_labels))
print("Seizure windows:", np.sum(loaded_labels))
print("Normal windows:", len(loaded_labels) - np.sum(loaded_labels))

Loaded labels shape: (900,)
Total windows: 900
Seizure windows: 10
Normal windows: 890
