In [1]:
import numpy as np


In [2]:
features = np.load("../data/features.npy")
labels = np.load("../data/labels.npy")

print(features.shape)
print(labels.shape)

(900, 8)
(900,)


In [3]:
from sklearn.model_selection import train_test_split


In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    features,
    labels,
    test_size=0.2,
    random_state=42
)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(720, 8)
(180, 8)
(720,)
(180,)


In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced"
)

In [24]:
model.fit(X_train, y_train)
print("Model Trained Successfully!")

Model Trained Successfully!


In [25]:
y_pred = model.predict(X_test)
print(y_pred[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [26]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy =", accuracy)

Accuracy = 0.9888888888888889


In [10]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       178
           1       0.00      0.00      0.00         2

    accuracy                           0.99       180
   macro avg       0.49      0.50      0.50       180
weighted avg       0.98      0.99      0.98       180



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [11]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[178   0]
 [  2   0]]


In [12]:
print("Training labels:")
print(np.unique(y_train, return_counts=True))

print("Testing labels:")
print(np.unique(y_test, return_counts=True))

Training labels:
(array([0, 1]), array([711,   9]))
Testing labels:
(array([0, 1]), array([178,   2]))


In [13]:
print(np.unique(y_pred, return_counts=True))
print(y_pred[:30])

(array([0]), array([180]))
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [14]:
import numpy as np
import pandas as pd

# Load data again
features = np.load("../data/features.npy")
labels = np.load("../data/labels.npy")

print("Features Shape :", features.shape)
print("Labels Shape :", labels.shape)

Features Shape : (900, 8)
Labels Shape : (900,)


In [15]:
feature_names = [
    "Mean",
    "Std",
    "Variance",
    "Delta",
    "Theta",
    "Alpha",
    "Beta",
    "Gamma"
]

df = pd.DataFrame(features, columns=feature_names)
df["Label"] = labels

print(df.head())

           Mean       Std      Variance         Delta         Theta  \
0  2.113283e-05  0.000061  3.720690e-09  1.414773e-09  3.423063e-10   
1 -3.544221e-06  0.000078  6.064531e-09  7.886706e-09  2.439176e-10   
2  4.042503e-06  0.000076  5.729106e-09  4.308287e-09  7.521715e-10   
3  6.328406e-07  0.000065  4.259692e-09  4.153795e-09  9.978408e-10   
4 -6.790920e-07  0.000049  2.442936e-09  1.316140e-09  4.032029e-10   

          Alpha          Beta         Gamma  Label  
0  1.139774e-10  3.370104e-10  1.906852e-10      0  
1  6.562713e-11  2.381540e-10  2.713703e-10      0  
2  8.927345e-11  2.767420e-10  2.144189e-10      0  
3  9.122084e-11  6.461378e-10  3.264995e-10      0  
4  8.699992e-11  4.359286e-10  2.405477e-10      0  


In [16]:
normal = df[df["Label"] == 0]
seizure = df[df["Label"] == 1]

print("Normal Windows :", len(normal))
print("Seizure Windows :", len(seizure))

Normal Windows : 889
Seizure Windows : 11


In [17]:
print("Normal Feature Mean")
print(normal.mean())

print("\n----------------------------\n")

print("Seizure Feature Mean")
print(seizure.mean())

Normal Feature Mean
Mean        2.540628e-08
Std         6.172705e-05
Variance    4.853181e-09
Delta       3.341858e-09
Theta       5.328073e-10
Alpha       9.307678e-11
Beta        3.079937e-10
Gamma       2.526086e-10
Label       0.000000e+00
dtype: float64

----------------------------

Seizure Feature Mean
Mean       -2.896785e-07
Std         6.870657e-05
Variance    6.170697e-09
Delta       5.220528e-09
Theta       3.219933e-10
Alpha       6.841324e-11
Beta        2.224342e-10
Gamma       1.608100e-10
Label       1.000000e+00
dtype: float64


In [18]:
print(normal.describe())

               Mean         Std      Variance         Delta         Theta  \
count  8.890000e+02  889.000000  8.890000e+02  8.890000e+02  8.890000e+02   
mean   2.540628e-08    0.000062  4.853181e-09  3.341858e-09  5.328073e-10   
std    3.337505e-06    0.000032  4.829740e-09  4.098151e-09  5.707610e-10   
min   -1.209887e-05    0.000013  1.606069e-10  3.181168e-11  1.332421e-11   
25%   -1.401971e-06    0.000033  1.060090e-09  2.881294e-10  7.801058e-11   
50%   -3.544356e-08    0.000060  3.557938e-09  1.739876e-09  3.384138e-10   
75%    1.374834e-06    0.000083  6.921577e-09  4.855556e-09  8.142674e-10   
max    2.113283e-05    0.000174  3.022100e-08  3.520535e-08  3.833000e-09   

              Alpha          Beta         Gamma  Label  
count  8.890000e+02  8.890000e+02  8.890000e+02  889.0  
mean   9.307678e-11  3.079937e-10  2.526086e-10    0.0  
std    1.338469e-10  6.213847e-10  4.368753e-10    0.0  
min    7.921772e-12  1.883006e-11  9.222103e-12    0.0  
25%    3.046743e-11  

In [19]:
 print(seizure.describe())

               Mean        Std      Variance         Delta         Theta  \
count  1.100000e+01  11.000000  1.100000e+01  1.100000e+01  1.100000e+01   
mean  -2.896785e-07   0.000069  6.170697e-09  5.220528e-09  3.219933e-10   
std    2.010516e-06   0.000040  5.739718e-09  6.948837e-09  3.883690e-10   
min   -3.200022e-06   0.000024  5.704861e-10  1.202282e-10  3.197611e-11   
25%   -1.896637e-06   0.000027  7.539984e-10  1.930310e-10  4.650042e-11   
50%    2.820474e-07   0.000074  5.472726e-09  1.532499e-09  1.607974e-10   
75%    1.188577e-06   0.000102  1.031814e-08  8.153362e-09  4.658815e-10   
max    2.610065e-06   0.000130  1.680685e-08  2.155343e-08  1.239433e-09   

              Alpha          Beta         Gamma  Label  
count  1.100000e+01  1.100000e+01  1.100000e+01   11.0  
mean   6.841324e-11  2.224342e-10  1.608100e-10    1.0  
std    7.255140e-11  8.803394e-11  9.540793e-11    0.0  
min    1.283968e-11  5.720391e-11  2.738505e-11    1.0  
25%    2.252280e-11  1.939053e

In [20]:
import pandas as pd

importance = pd.DataFrame({
    "Feature": feature_names,
    "Importance": model.feature_importances_
})

importance = importance.sort_values(by="Importance", ascending=False)

print(importance)

    Feature  Importance
4     Theta    0.149418
1       Std    0.146406
3     Delta    0.125861
2  Variance    0.121446
7     Gamma    0.120524
5     Alpha    0.118760
6      Beta    0.110652
0      Mean    0.106933


In [21]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       178
           1       0.00      0.00      0.00         2

    accuracy                           0.99       180
   macro avg       0.49      0.50      0.50       180
weighted avg       0.98      0.99      0.98       180



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [28]:
import joblib 
joblib.dump(model, "../data/random_forest_model.pkl")
print("Model Saved Successfully!")

Model Saved Successfully!


In [29]:
import joblib
joblib.dump(model, "../models/random_forest_model.pkl")
print("Model Saved Successfully!")

Model Saved Successfully!
