In [1]:
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.metrics import (
accuracy_score,
classification_report,
confusion_matrix,
)
import matplotlib.pyplot as plt

In [4]:
features = np.load("../data/features.npy")
labels = np.load("../data/labels.npy")

model = joblib.load("../data/random_forest_model.pkl")

print("Features:", features.shape)
print("Labels:", labels.shape)

Features: (900, 8)
Labels: (900,)


In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    features,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)

In [7]:
y_pred = model.predict(X_test)
print(y_pred[:20])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [8]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy =", accuracy)

Accuracy = 1.0


In [9]:
print(confusion_matrix(y_test, y_pred))

[[178   0]
 [  0   2]]


In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       178
           1       1.00      1.00      1.00         2

    accuracy                           1.00       180
   macro avg       1.00      1.00      1.00       180
weighted avg       1.00      1.00      1.00       180



In [12]:
print(np.unique(y_pred, return_counts = True))

(array([0, 1]), array([178,   2]))


In [13]:
print(np.unique(labels, return_counts = True))

(array([0, 1]), array([889,  11]))


In [14]:
print(features.shape)

(900, 8)
